# Generated by Django 5.2.1 on 2025-06-10 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0002_client_owner_mailing_owner_mailingattempt_owner_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'permissions': [('view_all', 'Может просматривать все объекты'), ('edit_all', 'Может редактировать все объекты')]},
        ),
        migrations.AlterModelOptions(
            name='mailing',
            options={'permissions': [('view_all', 'Может просматривать все объекты'), ('edit_all', 'Может редактировать все объекты')]},
        ),
        migrations.AlterModelOptions(
            name='mailingattempt',
            options={'permissions': [('view_all', 'Может просматривать все объекты'), ('edit_all', 'Может редактировать все объекты')]},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'permissions': [('view_all', 'Может просматривать все объекты'), ('edit_all', 'Может редактировать все объекты')]},
        ),
    ]
